database:
  host: localhost
  port: 3306
  database: rome # name of database
  username: user
  password: pass

land:
  cityMultiplier: 3
  suburbsMultiplier: 5

claims:
  claimMaterial: BRICK # material to set claims with
  claimTimeoutMS: 20000 # set to 0 for none
  defaultClaimBlocks: 400
  autoLockedBlocks:
    - CHEST
    - BARREL
    - ANVIL
    - BEACON
    - BLAST_FURNACE
    - FURNACE
    - SMOKER
    - CHEST_MINECART
    - FURNACE_MINECART
    - HOPPER
    - HOPPER_MINECART
    - BREWING_STAND
    - ITEM_FRAME
    - TRAPPED_CHEST
    - ARMOR_STAND
    - DROPPER
    - DISPENSER
    - CHIPPED_ANVIL
    - DAMAGED_ANVIL
    - SHULKER_BOX
    - BLACK_SHULKER_BOX
    - RED_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - PINK_SHULKER_BOX
    - LIME_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - OAK_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - CRIMSON_DOOR
    - WARPED_DOOR
  
messages:
  useSwearFilter: 1 # 0 for no filter, 1 for only city/government, and 2 for global
  messageDistance: 150 # distance to broadcast messages locally (0 for infinite distance)