database:
  host: localhost
  port: 3306
  database: rome # name of database
  username: user
  password: pass

land:
  cityMultiplier: 3 # the amount to multiply by your initial area to get the city area
  suburbsMultiplier: 5 # the amount to multiply by your initial number to get the suburbs area (suburbs area = city multiplier * suburbs multiplier * your initial number)

claims:
  claimMaterial: BRICK # material to set claims with
  claimTimeoutMS: 20000 # set to 0 for none
  defaultClaimBlocks: 400
  protectedLevel: GOVERNMENT # NONE, SUBURBS, CITY, or GOVERNMENT. If you choose SUBURBS, the city/government will be protected as well.
  autoLockedBlocks:
    - CHEST
    - BARREL
    - ANVIL
    - BEACON
    - BLAST_FURNACE
    - FURNACE
    - SMOKER
    - CHEST_MINECART
    - FURNACE_MINECART
    - HOPPER
    - HOPPER_MINECART
    - BREWING_STAND
    - ITEM_FRAME
    - TRAPPED_CHEST
    - ARMOR_STAND
    - DROPPER
    - DISPENSER
    - CHIPPED_ANVIL
    - DAMAGED_ANVIL
    - SHULKER_BOX
    - BLACK_SHULKER_BOX
    - RED_SHULKER_BOX
    - GREEN_SHULKER_BOX
    - BROWN_SHULKER_BOX
    - BLUE_SHULKER_BOX
    - PURPLE_SHULKER_BOX
    - CYAN_SHULKER_BOX
    - LIGHT_GRAY_SHULKER_BOX
    - GRAY_SHULKER_BOX
    - PINK_SHULKER_BOX
    - LIME_SHULKER_BOX
    - YELLOW_SHULKER_BOX
    - LIGHT_BLUE_SHULKER_BOX
    - MAGENTA_SHULKER_BOX
    - ORANGE_SHULKER_BOX
    - WHITE_SHULKER_BOX
    - OAK_DOOR
    - SPRUCE_DOOR
    - BIRCH_DOOR
    - JUNGLE_DOOR
    - ACACIA_DOOR
    - DARK_OAK_DOOR
    - CRIMSON_DOOR
    - WARPED_DOOR
  
messages:
  useSwearFilter: CITY # NEVER, SUBURBS, CITY, GOVERNMENT, or ALWAYS. This controls the area the swear filter applies to 
  messageDistance: 150 # distance to broadcast messages locally (0 for infinite distance)

webhooks:
  webhookurl: '' # replace with discord webhook URL for election announcements
  title: romeplugin # webhook title
  avatar_url: ~ # replace ~ with webhook avatar (if you want to)
