database:
  host: localhost
  port: 3306
  database: rome # name of database
  username: user
  password: pass

land:
  cityMultiplier: 3
  suburbsMultiplier: 5

claims:
  claimMaterial: BRICK # material to set claims with
  claimTimeoutMS: 20000 # set to 0 for none

messages:
  useSwearFilter: true 
  messageDistance: 250 # distance to broadcast messages locally (0 for infinite distance)