database:
  host: localhost
  port: 3306
  database: rome # name of database
  username: user
  password: pass

land:
  cityMultiplier: 3
  suburbsMultiplier: 5

claims:
  claimMaterial: BRICK # material to set claims with
  claimTimeoutMS: 20000 # set to 0 for none
  defaultClaimBlocks: 400
  autoLockedBlocks:
    - CHEST
    - BARREL
    - ANVIL
    - BEACON
    - BLAST_FURNACE
    - FURNACE
    - SMOKER
    - CHEST_MINECART
    - FURNACE_MINECART
    - HOPPER
    - HOPPER_MINECART
    - BREWING_STAND
    - ITEM_FRAME
    - TRAPPED_CHEST
    - ARMOR_STAND
    - SHULKER_BOX
    - DROPPER
    - DISPENSER
    - CHIPPED_ANVIL
    - DAMAGED_ANVIL
  
messages:
  useSwearFilter: 1 # 0 for no filter, 1 for only city/government, and 2 for global
  messageDistance: 250 # distance to broadcast messages locally (0 for infinite distance)