name: romeplugin
author: gose
version: 1.0
main: romeplugin.RomePlugin
api-version: 1.16
permissions:
  romeplugin.aedile:
    description: "aedile :)"
    default: op
commands:
  checktitle:
    description: "SycPrsFacNem"
    usage: "/checktitle <player>"
  removetitle:
    description: "remove a title from someone :)"
    usage: "/removetitle <player>"
    permission: op
  settitle:
    description: "MekSumPrsHavSumFacNem"
    usage: "/settitle <player> <title>"
    permission: op
  listtitles:
    description: "List current titles"
    usage: "/listtitles"
  foundrome:
    description: "it was made in a day :)"
    usage: "/foundrome [size]"
    permission: op
  pay:
    description: "pay someone"
    usage: "/pay <who>"
  bal:
    description: "get balance"
    usage: "/bal"
  claim:
    description: "claim land in the city :)"
    usage: "/claim radius <r> | /claim <x0> <y0> <x1> <y1>"
  claiminfo:
    description: "get information on the claim you are in"
    usage: "/claiminfo"
  killclaim:
    description: "remove a claim at your location"
    usage: "/killclaim"