name: romeplugin
author: gose
version: 1.0
main: romeplugin.RomePlugin
api-version: 1.16
permissions:
  romeplugin.aedile:
    description: "Mayor"
    default: op
  romeplugin.quaestor:
    description: "Senator"
commands:
  checktitle:
    description: "SycPrsFacNem"
    usage: "/checktitle <player>"
  removetitle:
    description: "remove a title from someone :)"
    usage: "/removetitle <player>"
    permission: op
  settitle:
    description: "MekSumPrsHavSumFacNem"
    usage: "/settitle <player> <title>"
    permission: op
  listtitles:
    description: "List current titles"
    usage: "/listtitles"
  foundrome:
    description: "it was made in a day :)"
    usage: "/foundrome [size]"
    permission: op
  bal:
    description: "get balance"
    usage: "/bal"
  claim:
    description: "claim land in the city :)"
    usage: "/claim radius <r> | /claim <x0> <y0> <x1> <y1>"
  claiminfo:
    description: "get information on the claim you are in"
    usage: "/claiminfo"
  killclaim:
    description: "remove a claim at your location"
    usage: "/killclaim"
  transferclaim:
    description: "transfer the claim you are in to someone else"
    usage: "/transferclaim <user>"
  rome:
    description: "do rome related things"
    usage: "/rome for help :)"
    permission: op
  builder:
    description: "deal with builders"
    usage: "/builder assign|revoke <who>"
    permission: romeplugin.aedile
  shout:
    description: "broadcast message globally"
    usage: "/shout [message]"
  pee:
    description: "take a piss"
    usage: "/pee"
  startelection:
    description: "start an election"
    permission: op
  vote:
    description: "vote for an election candidate"
    usage: "/vote <user>"
  run:
    description: "run for a position in an election"
    usage: "/run <position>"
    permission: romeplugin.quaestor
  
  makekey:
    description: "make a key out of the currently held item"
    usage: "/makekey"
