name: romeplugin
author: gose
version: 1.0
main: romeplugin.RomePlugin
api-version: 1.16
permissions:
  romeplugin.aedile:
    description: "Mayor"
    default: op
  romeplugin.quaestor:
    description: "Senator"
    default: op
  romeplugin.censor:
    description: "Censor"
    default: op
  romeplugin.consul:
    description: "Consul"
    default: op
  romeplugin.praetor:
    description: "Praetor"
    default: op
  romeplugin.tribune:
    description: "Tribune of the Plebs"
    default: op
  romeplugin.pope:
    description: "Pontifex Maximus"
    default: op
  romeplugin.builder:
    description: "Builder"
    default: op
commands:
  checktitle:
    description: "SycPrsFacNem"
    usage: "/checktitle <player>"
  removetitle:
    description: "remove a title from someone :)"
    usage: "/removetitle <player>"
    permission: op
  settitle:
    description: "MekSumPrsHavSumFacNem"
    usage: "/settitle <player> <title>"
    permission: op
  listtitles:
    description: "List current titles"
    usage: "/listtitles"
  foundrome:
    description: "it was made in a day :)"
    usage: "/foundrome [size]"
    permission: op
  bal:
    description: "get balance"
    usage: "/bal"
  claim:
    description: "claim land in the city :)"
    usage: "/claim radius <r> | /claim <x0> <y0> <x1> <y1>"
  claiminfo:
    description: "get information on the claim you are in"
    usage: "/claiminfo"
  getblocks:
    description: "get blocks owned by yourself"
    usage: "/getblocks [who]"
  killclaim:
    description: "remove a claim at your location"
    usage: "/killclaim"
  killallclaims:
    description: "remove all of your claims"
    usage: "/killallclaims <optional user>"
  transferclaim:
    description: "transfer claim to another player"
    usage: "/transferclaim <user>"
  rome:
    description: "do rome related things"
    usage: "/rome for help :)"
    permission: op
  builder:
    description: "deal with builders"
    usage: "/builder list|assign <who>|revoke <who>"
    permission: romeplugin.aedile
  shout:
    description: "broadcast message globally"
    usage: "/shout [message]"
  pee:
    description: "take a piss"
    usage: "/pee"
  elections:
    description: "type /elections help for help"
    usage: "/elections help"
  makekey:
    description: "make a key out of the currently held item"
    usage: "/makekey"
    permission: op